### ISSUE TITLE
Database not updating existing customer's info

### ISSUE THREAD

**Issue by jack-sherman** [wpapsco/capstone-mockup#53]
Current query just adds a new customer every time one goes through the checkout. We need to lookup customers to see if they already exist in the db before adding them.

**Comment by Zilarrezko** [comment]
If we find a match in the database for the email, what do we do?
For now the server will at least not insert a new customer. I guess we can update seating accommodation given the form data.
Do we want to update everything? It makes sense that phone numbers and addresses can change, so maybe those, perhaps name too. I guess everything _can_ change and maybe should change.
I will make the changes to address updating customer info. Meanwhile... thoughts?

**Comment by jack-sherman** [comment]
I think we should definitely update everything. Customers are only getting added during the checkout flow, so we'd definitely want addresses to get updated if they ever decided to have some sort of purchasable merch. Phone numbers will be useful for something like clarifying a seating accommodation. Someone might have a new seating accommodation entirely or could also change their mind on wanting to be on the newsletter.

**Comment by Zilarrezko** [comment]
Very fair, I'll merge into main then close the issue.
